attempt to toggle pause button
sirodoht/ketchup pull request #5
Opened 2017-03-08 09:30 UTC by hsoc

Haven't tested it. It "should" work (c) :-p

2017-03-08 12:25 UTC, sirodoht commented
Hey @hsoc! Thanks for the PR!

So, there are two issues with the code. The first is that in lines 184 and 186 you don't actually call those functions. You would need to use parenthesis to actually call them, i.e. `this.start()` instead of `this.start`.

The second problem is that in line 183 you use the function `this.start` to check if the timer is stopped or not. This won't work because the start function does not return something that can be evaluated as either true or false. (also the same problem applies as before, you need to use `()`)

So, the if statement in 183 will always evaluate as false, because `this.start` will always return the function object, which is true, and with `!` it will become false

2017-03-09 08:22 UTC, hsoc commented
Oops. :-) @sirodoht

2017-03-09 14:50 UTC, sirodoht requested changes
Mainly two corrections and it's done!

2017-03-09 14:50 UTC, sirodoht commented on app/main.js
> +    currentTask.paused === 'false'
This is a variable assignment, so you need to use `=`, not the conditional operator `===`.

Also, `false` is not a string. So, just `false`, with no quotes.

2017-03-09 14:50 UTC, sirodoht commented on app/main.js
> +    currentTask.paused = true
This is correct, but you need to find the `currentTask` first. So, just above this line, copy the line from line 172, i.e. `const currentTask = find(this.state.tasksList, {current: true})`

Then, when we assign `currentTask.paused = true`, the `currentTask` will be known.

2017-03-09 14:50 UTC, sirodoht commented on app/main.js
> +    if(currentTask.paused === 'true') {
Same thing with the above comment [1] here. You need to find the `currentTask` first.

Also, some thing with true. Just `true`, not `'true'` (no quotes)

[1] https://github.com/sirodoht/ketchup/pull/5/files/4643cd197cc477d785a032da8b8c0d3c96101715..6441c0dbe1e239278ea4194a25d320719f3f3978#r105179502

2017-03-09 15:07 UTC, sirodoht approved these changes

2017-03-09 15:07 UTC, merged